INSERT INTO "teams" VALUES(1,'Amazon');
INSERT INTO "teams" VALUES(2,'Dropbox');
INSERT INTO "teams" VALUES(3,'Facebook');
INSERT INTO "teams" VALUES(4,'Google');
INSERT INTO "teams" VALUES(5,'Microsoft');
INSERT INTO "teams" VALUES(6,'Twitter');
INSERT INTO "teams" VALUES(7,'Yelp');
INSERT INTO "teams" VALUES(8,'Zynga');
INSERT INTO "matches" VALUES(1,1,6,8);
INSERT INTO "matches" VALUES(1,2,3,2);
INSERT INTO "matches" VALUES(1,3,7,1);
INSERT INTO "matches" VALUES(1,4,5,4);
INSERT INTO "matches" VALUES(2,1,2,6);
INSERT INTO "matches" VALUES(2,2,8,1);
INSERT INTO "matches" VALUES(2,3,3,4);
INSERT INTO "matches" VALUES(2,4,7,5);
INSERT INTO "maps" VALUES(1,1,'Xel''Naga Caverns');
INSERT INTO "maps" VALUES(1,2,'Tal''Darim Altar');
INSERT INTO "maps" VALUES(1,3,'Backwater Gulch');
INSERT INTO "maps" VALUES(1,4,'Metalopolis');
INSERT INTO "maps" VALUES(1,5,'Shattered Temple');
INSERT INTO "maps" VALUES(2,1,'Shakuras Plateau');
INSERT INTO "maps" VALUES(2,2,'Xel''Naga Caverns');
INSERT INTO "maps" VALUES(2,3,'Typhon Peaks');
INSERT INTO "maps" VALUES(2,4,'Metalopolis');
INSERT INTO "maps" VALUES(2,5,'Tal''Darim Altar');
